// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Classification schema resource model. */
@Immutable
public final class ClassificationSchema {
    /*
     * Classification schema identifier.
     */
    @JsonProperty(value = "name", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String name;

    /*
     * Classification schema definition (JSON schema as string).
     */
    @JsonProperty(value = "schemaDefinition", required = true)
    private String schemaDefinition;

    /*
     * The entity tag for this resource.
     */
    @JsonProperty(value = "etag", required = true)
    private String etag;

    /**
     * Creates an instance of ClassificationSchema class.
     *
     * @param schemaDefinition the schemaDefinition value to set.
     * @param etag the etag value to set.
     */
    @JsonCreator
    private ClassificationSchema(
            @JsonProperty(value = "schemaDefinition", required = true) String schemaDefinition,
            @JsonProperty(value = "etag", required = true) String etag) {
        this.schemaDefinition = schemaDefinition;
        this.etag = etag;
    }

    /**
     * Get the name property: Classification schema identifier.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Get the schemaDefinition property: Classification schema definition (JSON schema as string).
     *
     * @return the schemaDefinition value.
     */
    public String getSchemaDefinition() {
        return this.schemaDefinition;
    }

    /**
     * Get the etag property: The entity tag for this resource.
     *
     * @return the etag value.
     */
    public String getEtag() {
        return this.etag;
    }
}
