// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** ClassificationSchema resource creation parameters. */
@Immutable
public final class ClassificationSchemaCreationParameters {
    /*
     * Classification schema definition (JSON schema as string).
     */
    @JsonProperty(value = "schemaDefinition", required = true)
    private String schemaDefinition;

    /**
     * Creates an instance of ClassificationSchemaCreationParameters class.
     *
     * @param schemaDefinition the schemaDefinition value to set.
     */
    @JsonCreator
    public ClassificationSchemaCreationParameters(
            @JsonProperty(value = "schemaDefinition", required = true) String schemaDefinition) {
        this.schemaDefinition = schemaDefinition;
    }

    /**
     * Get the schemaDefinition property: Classification schema definition (JSON schema as string).
     *
     * @return the schemaDefinition value.
     */
    public String getSchemaDefinition() {
        return this.schemaDefinition;
    }
}
