// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Request parameters for the complete upload metadata file API. */
@Immutable
public final class CompleteUploadMetadataFileRequest {
    /*
     * The ETag of the uploaded metadata file
     */
    @JsonProperty(value = "pendingFileETag", required = true)
    private String pendingFileETag;

    /**
     * Creates an instance of CompleteUploadMetadataFileRequest class.
     *
     * @param pendingFileETag the pendingFileETag value to set.
     */
    @JsonCreator
    public CompleteUploadMetadataFileRequest(
            @JsonProperty(value = "pendingFileETag", required = true) String pendingFileETag) {
        this.pendingFileETag = pendingFileETag;
    }

    /**
     * Get the pendingFileETag property: The ETag of the uploaded metadata file.
     *
     * @return the pendingFileETag value.
     */
    public String getPendingFileETag() {
        return this.pendingFileETag;
    }
}
