// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for DataStreamType. */
public final class DataStreamType extends ExpandableStringEnum<DataStreamType> {
    /** Static value System for DataStreamType. */
    public static final DataStreamType SYSTEM = fromString("System");

    /** Static value Raw for DataStreamType. */
    public static final DataStreamType RAW = fromString("Raw");

    /** Static value Derived for DataStreamType. */
    public static final DataStreamType DERIVED = fromString("Derived");

    /**
     * Creates or finds a DataStreamType from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding DataStreamType.
     */
    @JsonCreator
    public static DataStreamType fromString(String name) {
        return fromString(name, DataStreamType.class);
    }

    /**
     * Gets known DataStreamType values.
     *
     * @return known DataStreamType values.
     */
    public static Collection<DataStreamType> values() {
        return values(DataStreamType.class);
    }
}
