// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Data-stream logs folder. */
@Immutable
public final class DataStreamLogsContainerBase {
    /*
     * SAS signed URI for accessing the logs container on Azure Storage.
     * This URI expires in 24 hours.
     */
    @JsonProperty(value = "logFolderUri", required = true)
    private String logFolderUri;

    /**
     * Creates an instance of DataStreamLogsContainerBase class.
     *
     * @param logFolderUri the logFolderUri value to set.
     */
    @JsonCreator
    private DataStreamLogsContainerBase(@JsonProperty(value = "logFolderUri", required = true) String logFolderUri) {
        this.logFolderUri = logFolderUri;
    }

    /**
     * Get the logFolderUri property: SAS signed URI for accessing the logs container on Azure Storage. This URI expires
     * in 24 hours.
     *
     * @return the logFolderUri value.
     */
    public String getLogFolderUri() {
        return this.logFolderUri;
    }
}
