// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

/** Data stream lineage information. */
@Immutable
public final class DataStreamLineage {
    /*
     * The data stream's metadata
     */
    @JsonProperty(value = "producerMetadata", required = true)
    private Map<String, String> producerMetadata;

    /*
     * The data stream's inputs
     */
    @JsonProperty(value = "inputs", required = true)
    private List<DataStreamInput> inputs;

    /**
     * Creates an instance of DataStreamLineage class.
     *
     * @param producerMetadata the producerMetadata value to set.
     * @param inputs the inputs value to set.
     */
    @JsonCreator
    public DataStreamLineage(
            @JsonProperty(value = "producerMetadata", required = true) Map<String, String> producerMetadata,
            @JsonProperty(value = "inputs", required = true) List<DataStreamInput> inputs) {
        this.producerMetadata = producerMetadata;
        this.inputs = inputs;
    }

    /**
     * Get the producerMetadata property: The data stream's metadata.
     *
     * @return the producerMetadata value.
     */
    public Map<String, String> getProducerMetadata() {
        return this.producerMetadata;
    }

    /**
     * Get the inputs property: The data stream's inputs.
     *
     * @return the inputs value.
     */
    public List<DataStreamInput> getInputs() {
        return this.inputs;
    }
}
