// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Data-stream input definition. */
@Fluent
public final class DataStreamInput {
    /*
     * The source data-stream identifier
     */
    @JsonProperty(value = "sourceDataStreamId", required = true)
    private String sourceDataStreamId;

    /*
     * Collection of the data stream's channels
     */
    @JsonProperty(value = "channels")
    private List<String> channels;

    /**
     * Creates an instance of DataStreamInput class.
     *
     * @param sourceDataStreamId the sourceDataStreamId value to set.
     */
    @JsonCreator
    public DataStreamInput(@JsonProperty(value = "sourceDataStreamId", required = true) String sourceDataStreamId) {
        this.sourceDataStreamId = sourceDataStreamId;
    }

    /**
     * Get the sourceDataStreamId property: The source data-stream identifier.
     *
     * @return the sourceDataStreamId value.
     */
    public String getSourceDataStreamId() {
        return this.sourceDataStreamId;
    }

    /**
     * Get the channels property: Collection of the data stream's channels.
     *
     * @return the channels value.
     */
    public List<String> getChannels() {
        return this.channels;
    }

    /**
     * Set the channels property: Collection of the data stream's channels.
     *
     * @param channels the channels value to set.
     * @return the DataStreamInput object itself.
     */
    public DataStreamInput setChannels(List<String> channels) {
        this.channels = channels;
        return this;
    }
}
