// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** DataStream resource creation parameters. */
@Immutable
public final class DataStreamCreationParameters {
    /*
     * The data stream lineage information
     */
    @JsonProperty(value = "lineage", required = true)
    private DataStreamLineage lineage;

    /**
     * Creates an instance of DataStreamCreationParameters class.
     *
     * @param lineage the lineage value to set.
     */
    @JsonCreator
    public DataStreamCreationParameters(@JsonProperty(value = "lineage", required = true) DataStreamLineage lineage) {
        this.lineage = lineage;
    }

    /**
     * Get the lineage property: The data stream lineage information.
     *
     * @return the lineage value.
     */
    public DataStreamLineage getLineage() {
        return this.lineage;
    }
}
