// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The data-stream classification. */
@Immutable
public final class DataStreamClassification {
    /*
     * Classification schema name.
     */
    @JsonProperty(value = "schemaName", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String schemaName;

    /*
     * Classification object model (JSON as string)
     */
    @JsonProperty(value = "classificationObject", required = true)
    private String classificationObject;

    /*
     * The entity tag for this resource.
     */
    @JsonProperty(value = "etag", required = true)
    private String etag;

    /**
     * Creates an instance of DataStreamClassification class.
     *
     * @param classificationObject the classificationObject value to set.
     * @param etag the etag value to set.
     */
    @JsonCreator
    private DataStreamClassification(
            @JsonProperty(value = "classificationObject", required = true) String classificationObject,
            @JsonProperty(value = "etag", required = true) String etag) {
        this.classificationObject = classificationObject;
        this.etag = etag;
    }

    /**
     * Get the schemaName property: Classification schema name.
     *
     * @return the schemaName value.
     */
    public String getSchemaName() {
        return this.schemaName;
    }

    /**
     * Get the classificationObject property: Classification object model (JSON as string).
     *
     * @return the classificationObject value.
     */
    public String getClassificationObject() {
        return this.classificationObject;
    }

    /**
     * Get the etag property: The entity tag for this resource.
     *
     * @return the etag value.
     */
    public String getEtag() {
        return this.etag;
    }
}
