// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** File upload information. */
@Immutable
public final class FileUploadInformation {
    /*
     * File name specified by the client
     */
    @JsonProperty(value = "clientFileName", required = true)
    private String clientFileName;

    /*
     * SAS signed URI for uploading (write) file to Azure Storage.
     * This URI expires in 24 hours.
     */
    @JsonProperty(value = "fileUri", required = true)
    private String fileUri;

    /**
     * Creates an instance of FileUploadInformation class.
     *
     * @param clientFileName the clientFileName value to set.
     * @param fileUri the fileUri value to set.
     */
    @JsonCreator
    private FileUploadInformation(
            @JsonProperty(value = "clientFileName", required = true) String clientFileName,
            @JsonProperty(value = "fileUri", required = true) String fileUri) {
        this.clientFileName = clientFileName;
        this.fileUri = fileUri;
    }

    /**
     * Get the clientFileName property: File name specified by the client.
     *
     * @return the clientFileName value.
     */
    public String getClientFileName() {
        return this.clientFileName;
    }

    /**
     * Get the fileUri property: SAS signed URI for uploading (write) file to Azure Storage. This URI expires in 24
     * hours.
     *
     * @return the fileUri value.
     */
    public String getFileUri() {
        return this.fileUri;
    }
}
