// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Data stream search by lineage query parameters. */
@Immutable
public final class FindDataStreamByLineageRequestParameters {
    /*
     * The data-stream lineage to search for
     */
    @JsonProperty(value = "lineage", required = true)
    private DataStreamLineage lineage;

    /**
     * Creates an instance of FindDataStreamByLineageRequestParameters class.
     *
     * @param lineage the lineage value to set.
     */
    @JsonCreator
    public FindDataStreamByLineageRequestParameters(
            @JsonProperty(value = "lineage", required = true) DataStreamLineage lineage) {
        this.lineage = lineage;
    }

    /**
     * Get the lineage property: The data-stream lineage to search for.
     *
     * @return the lineage value.
     */
    public DataStreamLineage getLineage() {
        return this.lineage;
    }
}
