// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for LongRunningOperationStatus. */
public final class LongRunningOperationStatus extends ExpandableStringEnum<LongRunningOperationStatus> {
    /** Static value Created for LongRunningOperationStatus. */
    public static final LongRunningOperationStatus CREATED = fromString("Created");

    /** Static value InProgress for LongRunningOperationStatus. */
    public static final LongRunningOperationStatus IN_PROGRESS = fromString("InProgress");

    /** Static value Succeeded for LongRunningOperationStatus. */
    public static final LongRunningOperationStatus SUCCEEDED = fromString("Succeeded");

    /** Static value Failed for LongRunningOperationStatus. */
    public static final LongRunningOperationStatus FAILED = fromString("Failed");

    /** Static value Canceled for LongRunningOperationStatus. */
    public static final LongRunningOperationStatus CANCELED = fromString("Canceled");

    /**
     * Creates or finds a LongRunningOperationStatus from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding LongRunningOperationStatus.
     */
    @JsonCreator
    public static LongRunningOperationStatus fromString(String name) {
        return fromString(name, LongRunningOperationStatus.class);
    }

    /**
     * Gets known LongRunningOperationStatus values.
     *
     * @return known LongRunningOperationStatus values.
     */
    public static Collection<LongRunningOperationStatus> values() {
        return values(LongRunningOperationStatus.class);
    }
}
