// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Measurement metadata file information model. */
@Immutable
public final class MeasurementMetadataFileInfoBase {
    /*
     * The measurement's metadata file name
     */
    @JsonProperty(value = "metadataFileName", required = true)
    private String metadataFileName;

    /*
     * SAS signed URI to measurement metadata file.
     * If file already exists on storage then ETag of this file will be returned in the response header.
     * This URI expires in 24 hours.
     */
    @JsonProperty(value = "metadataFileUri", required = true)
    private String metadataFileUri;

    /*
     * The entity tag for the response.
     */
    @JsonProperty(value = "etagHeader", access = JsonProperty.Access.WRITE_ONLY)
    private String etagHeader;

    /**
     * Creates an instance of MeasurementMetadataFileInfoBase class.
     *
     * @param metadataFileName the metadataFileName value to set.
     * @param metadataFileUri the metadataFileUri value to set.
     */
    @JsonCreator
    private MeasurementMetadataFileInfoBase(
            @JsonProperty(value = "metadataFileName", required = true) String metadataFileName,
            @JsonProperty(value = "metadataFileUri", required = true) String metadataFileUri) {
        this.metadataFileName = metadataFileName;
        this.metadataFileUri = metadataFileUri;
    }

    /**
     * Get the metadataFileName property: The measurement's metadata file name.
     *
     * @return the metadataFileName value.
     */
    public String getMetadataFileName() {
        return this.metadataFileName;
    }

    /**
     * Get the metadataFileUri property: SAS signed URI to measurement metadata file. If file already exists on storage
     * then ETag of this file will be returned in the response header. This URI expires in 24 hours.
     *
     * @return the metadataFileUri value.
     */
    public String getMetadataFileUri() {
        return this.metadataFileUri;
    }

    /**
     * Get the etagHeader property: The entity tag for the response.
     *
     * @return the etagHeader value.
     */
    public String getEtagHeader() {
        return this.etagHeader;
    }
}
