// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/** Processing object node information in a processing objects Graph. */
@Immutable
public final class ProcessingObject {
    /*
     * The processing object metadata
     */
    @JsonProperty(value = "metadata", required = true)
    private Map<String, String> metadata;

    /*
     * A request unique ID to identify processing objects in graph
     */
    @JsonProperty(value = "id", required = true)
    private String id;

    /**
     * Creates an instance of ProcessingObject class.
     *
     * @param metadata the metadata value to set.
     * @param id the id value to set.
     */
    @JsonCreator
    public ProcessingObject(
            @JsonProperty(value = "metadata", required = true) Map<String, String> metadata,
            @JsonProperty(value = "id", required = true) String id) {
        this.metadata = metadata;
        this.id = id;
    }

    /**
     * Get the metadata property: The processing object metadata.
     *
     * @return the metadata value.
     */
    public Map<String, String> getMetadata() {
        return this.metadata;
    }

    /**
     * Get the id property: A request unique ID to identify processing objects in graph.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }
}
