// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** State machine. */
@Immutable
public final class StateMachine {
    /*
     * The state machine identifier.
     */
    @JsonProperty(value = "id", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String id;

    /*
     * Type of the state machine
     */
    @JsonProperty(value = "type", required = true)
    private String type;

    /*
     * Type of the state machine
     */
    @JsonProperty(value = "availableActionNames", required = true)
    private List<String> availableActionNames;

    /**
     * Creates an instance of StateMachine class.
     *
     * @param type the type value to set.
     * @param availableActionNames the availableActionNames value to set.
     */
    @JsonCreator
    private StateMachine(
            @JsonProperty(value = "type", required = true) String type,
            @JsonProperty(value = "availableActionNames", required = true) List<String> availableActionNames) {
        this.type = type;
        this.availableActionNames = availableActionNames;
    }

    /**
     * Get the id property: The state machine identifier.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Get the type property: Type of the state machine.
     *
     * @return the type value.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Get the availableActionNames property: Type of the state machine.
     *
     * @return the availableActionNames value.
     */
    public List<String> getAvailableActionNames() {
        return this.availableActionNames;
    }
}
