// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** A data-stream tags. */
@Immutable
public final class TagSet {
    /*
     * The data stream tag set identifier.
     * Not in use as this is a singleton resource. Tags could be set or returned as singleton set.
     * TODO: check with CADL team how to define a singleton child resource without key.
     */
    @JsonProperty(value = "id", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String id;

    /*
     * Set of data-stream tags.
     */
    @JsonProperty(value = "tags", required = true)
    private List<Tag> tags;

    /**
     * Creates an instance of TagSet class.
     *
     * @param tags the tags value to set.
     */
    @JsonCreator
    private TagSet(@JsonProperty(value = "tags", required = true) List<Tag> tags) {
        this.tags = tags;
    }

    /**
     * Get the id property: The data stream tag set identifier. Not in use as this is a singleton resource. Tags could
     * be set or returned as singleton set. TODO: check with CADL team how to define a singleton child resource without
     * key.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Get the tags property: Set of data-stream tags.
     *
     * @return the tags value.
     */
    public List<Tag> getTags() {
        return this.tags;
    }
}
