// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/** A measurement resource created as result of the upload. */
@Immutable
public final class UploadResultMeasurement {
    /*
     * Measurement identifier.
     */
    @JsonProperty(value = "measurementId", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String measurementId;

    /** Creates an instance of UploadResultMeasurement class. */
    private UploadResultMeasurement() {}

    /**
     * Get the measurementId property: Measurement identifier.
     *
     * @return the measurementId value.
     */
    public String getMeasurementId() {
        return this.measurementId;
    }
}
