// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** The supported operations of the upload. */
public final class UploadOperationType extends ExpandableStringEnum<UploadOperationType> {
    /** Static value FinalizeFileList for UploadOperationType. */
    public static final UploadOperationType FINALIZE_FILE_LIST = fromString("FinalizeFileList");

    /** Static value ShardFiles for UploadOperationType. */
    public static final UploadOperationType SHARD_FILES = fromString("ShardFiles");

    /** Static value CompleteUpload for UploadOperationType. */
    public static final UploadOperationType COMPLETE_UPLOAD = fromString("CompleteUpload");

    /** Static value AbortUpload for UploadOperationType. */
    public static final UploadOperationType ABORT_UPLOAD = fromString("AbortUpload");

    /**
     * Creates or finds a UploadOperationType from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding UploadOperationType.
     */
    @JsonCreator
    public static UploadOperationType fromString(String name) {
        return fromString(name, UploadOperationType.class);
    }

    /**
     * Gets known UploadOperationType values.
     *
     * @return known UploadOperationType values.
     */
    public static Collection<UploadOperationType> values() {
        return values(UploadOperationType.class);
    }
}
