// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.
package com.adp.datamanagement;

import com.adp.datamanagement.models.TagSet;
import com.adp.datamanagement.models.TagSetBase;
import com.adp.datamanagement.models.TagSetCreationParameters;
import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;

/** Initializes a new instance of the synchronous DataStreamTagsClient type. */
@ServiceClient(builder = DataStreamTagsClientBuilder.class)
public final class DataStreamTagsClient {

    @Generated private final DataStreamTagsAsyncClient client;

    /**
     * Initializes an instance of DataStreamTagsClient class.
     *
     * @param client the async client.
     */
    @Generated
    DataStreamTagsClient(DataStreamTagsAsyncClient client) {
        this.client = client;
    }

    /**
     * Returns set of the data-stream tags.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     id: String (Required)
     *     tags (Required): [
     *          (Required){
     *             key: String (Required)
     *             value: String (Required)
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return a data-stream tags along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> getWithResponse(
            String measurementId, String dataStreamId, RequestOptions requestOptions) {
        return this.client.getWithResponse(measurementId, dataStreamId, requestOptions).block();
    }

    /**
     * Create or replace all tags at once.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     tags (Required): [
     *          (Required){
     *             key: String (Required)
     *             value: String (Required)
     *         }
     *     ]
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     tags (Required): [
     *          (Required){
     *             key: String (Required)
     *             value: String (Required)
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return tag set along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createWithResponse(
            String measurementId, String dataStreamId, RequestOptions requestOptions) {
        return this.client.createWithResponse(measurementId, dataStreamId, requestOptions).block();
    }

    /**
     * Returns set of the data-stream tags.
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.exception.HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a data-stream tags.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public TagSet get(String measurementId, String dataStreamId) {
        // Generated convenience method for getWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getWithResponse(measurementId, dataStreamId, requestOptions).getValue().toObject(TagSet.class);
    }

    /**
     * Create or replace all tags at once.
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @param body Parameter of type 'TagSetCreationParameters' in the body.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.exception.HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return tag set.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public TagSetBase create(String measurementId, String dataStreamId, TagSetCreationParameters body) {
        // Generated convenience method for createWithResponse
        RequestOptions requestOptions = new RequestOptions();
        if (body != null) {
            requestOptions.setBody(BinaryData.fromObject(body));
        }
        return createWithResponse(measurementId, dataStreamId, requestOptions).getValue().toObject(TagSetBase.class);
    }

    /**
     * Create or replace all tags at once.
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.exception.HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return tag set.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public TagSetBase create(String measurementId, String dataStreamId) {
        // Generated convenience method for createWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createWithResponse(measurementId, dataStreamId, requestOptions).getValue().toObject(TagSetBase.class);
    }
}
