// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.
package com.adp.datamanagement;

import com.adp.datamanagement.implementation.DataStreamStorageClientImpl;
import com.adp.datamanagement.models.StorageBase;
import com.adp.datamanagement.models.StorageCreationParameters;
import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;
import com.azure.core.util.FluxUtil;
import reactor.core.publisher.Mono;

/** Initializes a new instance of the asynchronous DataStreamStorageClient type. */
@ServiceClient(builder = DataStreamStorageClientBuilder.class, isAsync = true)
public final class DataStreamStorageAsyncClient {

    @Generated private final DataStreamStorageClientImpl serviceClient;

    /**
     * Initializes an instance of DataStreamStorageAsyncClient class.
     *
     * @param serviceClient the service client implementation.
     */
    @Generated
    DataStreamStorageAsyncClient(DataStreamStorageClientImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Create or replace storage information of the data-stream. Returns the data-stream storage resource with SAS
     * signed URIs that allow uploading to Azure Storage. The SAS token expires in 24 hours.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     type: String (Required)
     *     rollingInformation (Optional): {
     *         strategy: String(Time/Size) (Required)
     *         unit: String(Seconds/Minutes/kB/MB/GB) (Required)
     *         value: int (Required)
     *     }
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     type: String (Required)
     *     rollingInformation (Optional): {
     *         strategy: String(Time/Size) (Required)
     *         unit: String(Seconds/Minutes/kB/MB/GB) (Required)
     *         value: int (Required)
     *     }
     *     manifestUri: String (Required)
     *     dataFolderUri: String (Optional)
     *     shards (Required): [
     *          (Required){
     *             shardFolderUri: String (Required)
     *             manifestFileUri: String (Required)
     *         }
     *     ]
     *     etag: String (Required)
     * }
     * }</pre>
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return common data-stream storage model along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> createWithResponse(
            String measurementId, String dataStreamId, RequestOptions requestOptions) {
        return this.serviceClient.createWithResponseAsync(measurementId, dataStreamId, requestOptions);
    }

    /**
     * Returns the data-stream storage resource with SAS signed URIs that allow uploading to Azure Storage. The SAS
     * token expires in 24 hours.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     type: String (Required)
     *     rollingInformation (Optional): {
     *         strategy: String(Time/Size) (Required)
     *         unit: String(Seconds/Minutes/kB/MB/GB) (Required)
     *         value: int (Required)
     *     }
     *     manifestUri: String (Required)
     *     dataFolderUri: String (Optional)
     *     shards (Required): [
     *          (Required){
     *             shardFolderUri: String (Required)
     *             manifestFileUri: String (Required)
     *         }
     *     ]
     *     etag: String (Required)
     * }
     * }</pre>
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return common data-stream storage model along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> getWritableUrisWithResponse(
            String measurementId, String dataStreamId, RequestOptions requestOptions) {
        return this.serviceClient.getWritableUrisWithResponseAsync(measurementId, dataStreamId, requestOptions);
    }

    /**
     * Create or replace storage information of the data-stream. Returns the data-stream storage resource with SAS
     * signed URIs that allow uploading to Azure Storage. The SAS token expires in 24 hours.
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @param body Parameter of type 'StorageCreationParameters' in the body.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.exception.HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return common data-stream storage model on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<StorageBase> create(String measurementId, String dataStreamId, StorageCreationParameters body) {
        // Generated convenience method for createWithResponse
        RequestOptions requestOptions = new RequestOptions();
        if (body != null) {
            requestOptions.setBody(BinaryData.fromObject(body));
        }
        return createWithResponse(measurementId, dataStreamId, requestOptions)
                .flatMap(FluxUtil::toMono)
                .map(protocolMethodData -> protocolMethodData.toObject(StorageBase.class));
    }

    /**
     * Create or replace storage information of the data-stream. Returns the data-stream storage resource with SAS
     * signed URIs that allow uploading to Azure Storage. The SAS token expires in 24 hours.
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.exception.HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return common data-stream storage model on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<StorageBase> create(String measurementId, String dataStreamId) {
        // Generated convenience method for createWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createWithResponse(measurementId, dataStreamId, requestOptions)
                .flatMap(FluxUtil::toMono)
                .map(protocolMethodData -> protocolMethodData.toObject(StorageBase.class));
    }

    /**
     * Returns the data-stream storage resource with SAS signed URIs that allow uploading to Azure Storage. The SAS
     * token expires in 24 hours.
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.exception.HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return common data-stream storage model on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<StorageBase> getWritableUris(String measurementId, String dataStreamId) {
        // Generated convenience method for getWritableUrisWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getWritableUrisWithResponse(measurementId, dataStreamId, requestOptions)
                .flatMap(FluxUtil::toMono)
                .map(protocolMethodData -> protocolMethodData.toObject(StorageBase.class));
    }
}
