// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.
package com.adp.datamanagement;

import com.adp.datamanagement.models.StorageBase;
import com.adp.datamanagement.models.StorageCreationParameters;
import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;

/** Initializes a new instance of the synchronous DataStreamStorageClient type. */
@ServiceClient(builder = DataStreamStorageClientBuilder.class)
public final class DataStreamStorageClient {

    @Generated private final DataStreamStorageAsyncClient client;

    /**
     * Initializes an instance of DataStreamStorageClient class.
     *
     * @param client the async client.
     */
    @Generated
    DataStreamStorageClient(DataStreamStorageAsyncClient client) {
        this.client = client;
    }

    /**
     * Create or replace storage information of the data-stream. Returns the data-stream storage resource with SAS
     * signed URIs that allow uploading to Azure Storage. The SAS token expires in 24 hours.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     type: String (Required)
     *     rollingInformation (Optional): {
     *         strategy: String(Time/Size) (Required)
     *         unit: String(Seconds/Minutes/kB/MB/GB) (Required)
     *         value: int (Required)
     *     }
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     type: String (Required)
     *     rollingInformation (Optional): {
     *         strategy: String(Time/Size) (Required)
     *         unit: String(Seconds/Minutes/kB/MB/GB) (Required)
     *         value: int (Required)
     *     }
     *     manifestUri: String (Required)
     *     dataFolderUri: String (Optional)
     *     shards (Required): [
     *          (Required){
     *             shardFolderUri: String (Required)
     *             manifestFileUri: String (Required)
     *         }
     *     ]
     *     etag: String (Required)
     * }
     * }</pre>
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return common data-stream storage model along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createWithResponse(
            String measurementId, String dataStreamId, RequestOptions requestOptions) {
        return this.client.createWithResponse(measurementId, dataStreamId, requestOptions).block();
    }

    /**
     * Returns the data-stream storage resource with SAS signed URIs that allow uploading to Azure Storage. The SAS
     * token expires in 24 hours.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     type: String (Required)
     *     rollingInformation (Optional): {
     *         strategy: String(Time/Size) (Required)
     *         unit: String(Seconds/Minutes/kB/MB/GB) (Required)
     *         value: int (Required)
     *     }
     *     manifestUri: String (Required)
     *     dataFolderUri: String (Optional)
     *     shards (Required): [
     *          (Required){
     *             shardFolderUri: String (Required)
     *             manifestFileUri: String (Required)
     *         }
     *     ]
     *     etag: String (Required)
     * }
     * }</pre>
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return common data-stream storage model along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> getWritableUrisWithResponse(
            String measurementId, String dataStreamId, RequestOptions requestOptions) {
        return this.client.getWritableUrisWithResponse(measurementId, dataStreamId, requestOptions).block();
    }

    /**
     * Create or replace storage information of the data-stream. Returns the data-stream storage resource with SAS
     * signed URIs that allow uploading to Azure Storage. The SAS token expires in 24 hours.
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @param body Parameter of type 'StorageCreationParameters' in the body.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.exception.HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return common data-stream storage model.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public StorageBase create(String measurementId, String dataStreamId, StorageCreationParameters body) {
        // Generated convenience method for createWithResponse
        RequestOptions requestOptions = new RequestOptions();
        if (body != null) {
            requestOptions.setBody(BinaryData.fromObject(body));
        }
        return createWithResponse(measurementId, dataStreamId, requestOptions).getValue().toObject(StorageBase.class);
    }

    /**
     * Create or replace storage information of the data-stream. Returns the data-stream storage resource with SAS
     * signed URIs that allow uploading to Azure Storage. The SAS token expires in 24 hours.
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.exception.HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return common data-stream storage model.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public StorageBase create(String measurementId, String dataStreamId) {
        // Generated convenience method for createWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createWithResponse(measurementId, dataStreamId, requestOptions).getValue().toObject(StorageBase.class);
    }

    /**
     * Returns the data-stream storage resource with SAS signed URIs that allow uploading to Azure Storage. The SAS
     * token expires in 24 hours.
     *
     * @param measurementId The measurement identifier.
     * @param dataStreamId The data stream identifier.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.exception.HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return common data-stream storage model.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public StorageBase getWritableUris(String measurementId, String dataStreamId) {
        // Generated convenience method for getWritableUrisWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getWritableUrisWithResponse(measurementId, dataStreamId, requestOptions)
                .getValue()
                .toObject(StorageBase.class);
    }
}
