// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.
package com.cadl.partialupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.core.util.CoreUtils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The PartialUpdateModel model. */
@Immutable
public final class PartialUpdateModel {

    /*
     * The boolean property.
     */
    @Generated
    @JsonProperty(value = "boolean", required = true)
    private boolean booleanProperty;

    /*
     * The string property.
     */
    @Generated
    @JsonProperty(value = "string", required = true)
    private String string;

    /*
     * The bytes property.
     */
    @Generated
    @JsonProperty(value = "bytes", required = true)
    private byte[] bytes;

    /**
     * Creates an instance of PartialUpdateModel class.
     *
     * @param booleanProperty the booleanProperty value to set.
     * @param string the string value to set.
     * @param bytes the bytes value to set.
     */
    @Generated
    @JsonCreator
    private PartialUpdateModel(
            @JsonProperty(value = "boolean", required = true) boolean booleanProperty,
            @JsonProperty(value = "string", required = true) String string,
            @JsonProperty(value = "bytes", required = true) byte[] bytes) {
        this.booleanProperty = booleanProperty;
        this.string = string;
        this.bytes = bytes;
    }

    /**
     * Get the booleanProperty property: The boolean property.
     *
     * @return the booleanProperty value.
     */
    @Generated
    public boolean isBooleanProperty() {
        return this.booleanProperty;
    }

    /**
     * Get the string property: The string property.
     *
     * @return the string value.
     */
    @Generated
    public String getString() {
        return this.string;
    }

    /**
     * Get the bytes property: The bytes property.
     *
     * @return the bytes value.
     */
    @Generated
    public byte[] getBytes() {
        return CoreUtils.clone(this.bytes);
    }
}
