// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.adp.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Special file resource. */
@Immutable
public final class UploadSpecialFile {
    /*
     * File name specified by the client
     */
    @JsonProperty(value = "clientFileName", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String clientFileName;

    /*
     * SAS signed URI for uploading file to Azure Storage.
     * This URI expires in 24 hours.
     */
    @JsonProperty(value = "fileUploadUri", required = true)
    private String fileUploadUri;

    /**
     * Creates an instance of UploadSpecialFile class.
     *
     * @param fileUploadUri the fileUploadUri value to set.
     */
    @JsonCreator
    private UploadSpecialFile(@JsonProperty(value = "fileUploadUri", required = true) String fileUploadUri) {
        this.fileUploadUri = fileUploadUri;
    }

    /**
     * Get the clientFileName property: File name specified by the client.
     *
     * @return the clientFileName value.
     */
    public String getClientFileName() {
        return this.clientFileName;
    }

    /**
     * Get the fileUploadUri property: SAS signed URI for uploading file to Azure Storage. This URI expires in 24 hours.
     *
     * @return the fileUploadUri value.
     */
    public String getFileUploadUri() {
        return this.fileUploadUri;
    }
}
