// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.adp.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.models.ResponseError;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The long running operation response. */
@Immutable
public final class UploadLroResponse {
    /*
     * The operation Id.
     */
    @JsonProperty(value = "operationId", required = true)
    private String operationId;

    /*
     * The operation status.
     */
    @JsonProperty(value = "status", required = true)
    private LongRunningOperationStatus status;

    /*
     * The operation type.
     */
    @JsonProperty(value = "operationType")
    private UploadOperationType operationType;

    /*
     * The operation error.
     */
    @JsonProperty(value = "error")
    private ResponseError error;

    /**
     * Creates an instance of UploadLroResponse class.
     *
     * @param operationId the operationId value to set.
     * @param status the status value to set.
     */
    @JsonCreator
    private UploadLroResponse(
            @JsonProperty(value = "operationId", required = true) String operationId,
            @JsonProperty(value = "status", required = true) LongRunningOperationStatus status) {
        this.operationId = operationId;
        this.status = status;
    }

    /**
     * Get the operationId property: The operation Id.
     *
     * @return the operationId value.
     */
    public String getOperationId() {
        return this.operationId;
    }

    /**
     * Get the status property: The operation status.
     *
     * @return the status value.
     */
    public LongRunningOperationStatus getStatus() {
        return this.status;
    }

    /**
     * Get the operationType property: The operation type.
     *
     * @return the operationType value.
     */
    public UploadOperationType getOperationType() {
        return this.operationType;
    }

    /**
     * Get the error property: The operation error.
     *
     * @return the error value.
     */
    public ResponseError getError() {
        return this.error;
    }
}
