// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement.implementation.models;

import com.adp.datamanagement.models.ClassificationSchema;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Paged collection of ClassificationSchema items. */
@Immutable
public final class PagedClassificationSchema {
    /*
     * The ClassificationSchema items on this page
     */
    @JsonProperty(value = "value", required = true)
    private List<ClassificationSchema> value;

    /*
     * The link to the next page of items
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Creates an instance of PagedClassificationSchema class.
     *
     * @param value the value value to set.
     */
    @JsonCreator
    private PagedClassificationSchema(
            @JsonProperty(value = "value", required = true) List<ClassificationSchema> value) {
        this.value = value;
    }

    /**
     * Get the value property: The ClassificationSchema items on this page.
     *
     * @return the value value.
     */
    public List<ClassificationSchema> getValue() {
        return this.value;
    }

    /**
     * Get the nextLink property: The link to the next page of items.
     *
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }
}
