// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.adp.datamanagement;

public final class ReadmeSamples {
    public void readmeSamples() {
        // BEGIN: com.adp.datamanagement.readme
        // END: com.adp.datamanagement.readme
    }
}
