// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.adp.datamanagement {
    requires transitive com.azure.core;

    exports com.adp.datamanagement;
}
