// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.adp;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.util.BinaryData;
import com.azure.core.util.polling.SyncPoller;

/** Initializes a new instance of the synchronous AutonomousDevelopmentPlatformClient type. */
@ServiceClient(builder = LongRunningOperationsClientBuilder.class)
public final class LongRunningOperationsClient {
    @Generated private final LongRunningOperationsAsyncClient client;

    /**
     * Initializes an instance of LongRunningOperationsClient class.
     *
     * @param client the async client.
     */
    @Generated
    LongRunningOperationsClient(LongRunningOperationsAsyncClient client) {
        this.client = client;
    }

    /**
     * Get the details of an LRO.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     status: String(Created/InProgress/Succeeded/Failed/Canceled) (Required)
     *     operationType: String (Optional)
     *     error: ResponseError (Optional)
     *     operationId: String (Required)
     * }
     * }</pre>
     *
     * @param operationId The operation Id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link SyncPoller} for polling of the details of an LRO.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.LONG_RUNNING_OPERATION)
    public SyncPoller<BinaryData, BinaryData> beginGet(String operationId, RequestOptions requestOptions) {
        return this.client.beginGet(operationId, requestOptions).getSyncPoller();
    }
}
